# import "../_fragments/Templates.gql"

query templates {
	templates {
		_id
		title
		location {
			_id
			title
			address
		}
		sessions {
			_id
			title
			startTime
			endTime
		}
		days {
			_id
			title
		}
		areas {
			_id
			title
			alternateName
		}
		staff
		allocationType
		createdAt
		updatedAt
	}
}

query editTemplate($_id: String) {
	template(_id: $_id) {
		_id
		title
		location {
			_id
			title
			address
		}
		sessions {
			_id
			title
			startTime
			endTime
		}
		days {
			_id
			title
		}
		areas {
			_id
			title
			alternateName
		}
		staff
		allocationType
	}
}

query template($_id: String, $sortBy: String) {
	template(_id: $_id) {
		_id
		title
		location {
			_id
			title
			address
		}
		sessions {
			_id
			title
			startTime
			endTime
		}
		days {
			_id
			title
		}
		areas {
			_id
			title
			alternateName
		}
		staff
		allocationType
	}
}