fragment UserAttributes on User {
  _id
  name {
    first
    last
  }
  avatarUrl
  username
  emailAddress
  emailVerified
  oAuthProvider
  roles {
    _id
    name
    inRole
  }
  entities {
    _id
    title
  }
  locations {
    _id
    title
  }
  class
  settings {
    _id
    key
    label
    type
    value 
  }
}
